"""initial migration

Revision ID: 501bcb3c9562
Revises: 
Create Date: 2025-02-24 11:51:36.559592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501bcb3c9562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
